import Head from 'next/head'
import Image from 'next/image'

type Props = {
    children: JSX.Element
};

export default function Layout({children}: Props) {
    return (
        <div>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="manifest" href="/manifest.json" />
                <link rel="apple-touch-icon" href="/icons/apple-touch-192.png"/>
                <meta name="theme-color" content="#d8b4fe"/>
            </Head>
            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
                    Share to <span className="text-purple-300"><br className="hej" />T3</span> App
                </h1>
                {children}
            </main>
        </div>)
}
